version: '3'
services:
  web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./wwwroot:/var/www/html
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
  php:
    build:
      context: ./php-fpm_PDO_MYSQL
    image: php-pdomysql
    volumes:
        - ./wwwroot:/var/www/html
  mysqldb:
    image: mariadb:10.4.6-bionic
    environment:
        - MYSQL_DATABASE=eqdkp
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=eqdkp
        - MYSQL_PASSWORD=eqdkp
    volumes:
        - /data/db/mysql:/var/lib/mysql